name: Deploy

on:
    push:
        branches:
            - main

jobs:
    deploy:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v2

            - name: Copy files to VPS
              uses: appleboy/scp-action@master
              with:
                  host: ${{ secrets.HOST_IP_ADDRESS }}
                  username: ${{ secrets.VPS_USERNAME }}
                  port: 22
                  key: ${{ secrets.VPS_PRIV_KEY }}
                  source: "."
                  target: "~/my-site"

            - name: Build and run Docker container
              uses: appleboy/ssh-action@master
              with:
                  host: ${{ secrets.HOST_IP_ADDRESS }}
                  username: ${{ secrets.VPS_USERNAME }}
                  port: 22
                  key: ${{ secrets.VPS_PRIV_KEY }}
                  script: |
                      cd ~/my-site
                      docker build -t me-nimal:v1 .
                      docker run -d -p 5100:80 me-nimal:v1
                      cd ~
                      rm -rf ~/my-site
